server:
  port: 8087
  servlet:
    context-path: /api/authorization
management:
  server:
    port: 8287
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:6666/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: authorization
  liquibase:
    default-schema: authorization
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: authorization-app
eureka:
  client:
    enabled: false
logging:
  level:
    org:
      springdoc: DEBUG
      hibernate:
        SQL: DEBUG
#        type: TRACE
